name: Setup Environment

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

      python_version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
