name: E2E Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Setup Environment
        uses: ../.github/actions/setup-env
        with:
          node_version: 20
          python_version: 3.12

      - name: Browser init
        run: rfbrowser init

      - name: Run E2E Tests
        run: robot -d ./logs -v BROWSER:${{ matrix.browser }} tests/web

      - name: Robot Reporter
        uses: joonvena/robotframework-reporter-action@v2.4
        if: always()
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: logs

      - name: Upload Report
        uses: actions/upload-artifact@v4.6.1
        if: always()
        with:
          name: ${{ matrix.browser }} Test report
          path: logs
