name: E2E Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node_version: 20
          python_version: 3.12

      - name: Browser init
        run: rfbrowser init

      - name: Run E2E Tests
        run: robot -d ./logs -v BROWSER:${{ matrix.browser }} tests/web

      - name: Reporter
        uses: ./.github/actions/reporter
        with:
          secret_github: ${{ secrets.GITHUB_TOKEN }}
          report_test_name: ${{ matrix.browser }}

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node_version: 20
          python_version: 3.12

      - name: Run API Tests
        run: robot -d ./logs tests/api

      - name: Reporter
        uses: ./.github/actions/reporter
        with:
          secret_github: ${{ secrets.GITHUB_TOKEN }}
          report_test_name: API
